#pragma once

#include <cstdint>

#include <glm/ext/vector_float3.hpp>
#include <glm/gtc/quaternion.hpp>

#include "../types.hpp"  // IWYU pragma: export

namespace ghoulies::objects
{

enum ObjectType : std::uint16_t
{
  None = 0
};

enum class ObjectTag : uint16_t
{
  Null = 0,
  Actor = 1,
  ActorBaron = 2,
  ActorBaronPlane = 3,
  ActorBoy = 4,
  ActorButler = 5,
  ActorCameron = 6,
  ActorChicken = 7,
  ActorCook = 8,
  ActorCookPlayable = 9,
  ActorDoll = 10,
  ActorFiddler = 11,
  ActorGhoulieGirl = 12,
  ActorGiantHand = 13,
  ActorGirl = 14,
  ActorGrimReaper = 15,
  ActorHauntedChair = 16,
  ActorHauntedCoat = 17,
  ActorHauntedDoor = 18,
  ActorHauntedDoorRound = 19,
  ActorHauntedPicture = 20,
  ActorHauntedTV = 21,
  ActorHunchback = 22,
  ActorImp = 23,
  ActorImpChallenge = 24,
  ActorImpFire = 25,
  ActorImpFlying = 26,
  ActorImpNinja = 27,
  ActorImpNinjaBig = 28,
  ActorImpRoger = 29,
  ActorJessieClyde = 30,
  ActorMedusa = 31,
  ActorMiniCooper = 32,
  ActorMrsMop = 33,
  ActorMummy = 34,
  ActorMummyCursed = 35,
  ActorPirate = 36,
  ActorPirateLeader = 37,
  ActorPrisonerChestChap = 38,
  ActorPrisonerDoggyGirl = 39,
  ActorPrisonerFilmReel = 40,
  ActorPrisonerFridgeLady = 41,
  ActorPrisonerFridgeLadyF = 42,
  ActorPrisonerLaundryLad = 43,
  ActorPrisonerPlatterLad = 44,
  ActorPrisonerSarco = 45,
  ActorPrisonerSaunaGirl = 46,
  ActorPrisonerSerpentYout = 47,
  ActorPrisonerThornGirl = 48,
  ActorRibs = 49,
  ActorRibsFNPC = 50,
  ActorRibsKey = 51,
  ActorSkeleton = 52,
  ActorSkeletonMaid = 53,
  ActorSpider = 54,
  ActorUglyGirl = 55,
  ActorVampire = 56,
  ActorVampireChicken = 57,
  ActorWarlock = 58,
  ActorWorm = 59,
  ActorZombie = 60,
  ActorZzz = 61,
  Avatar = 62,
  AvatarDizzyBat = 63,
  AvatarFxAnimEmitter = 64,
  AvatarFxBurnUp = 65,
  AvatarFxExplode = 66,
  AvatarFxMotionBlur = 67,
  AvatarHatstandBase = 68,
  AvatarStandardLampBase = 69,
  Background = 70,
  BgBreakKey = 71,
  Body = 72,
  BodyCamera = 73,
  BodyHuman = 74,
  BodyJessieClyde = 75,
  BodyPlayer = 76,
  BodyVampire = 77,
  BodyZombie = 78,
  Camera = 79,
  FxCustomDustUp = 80,
  FxCustomElectric = 81,
  FxCustomFadeOut = 82,
  FxCustomFadeToGrey = 83,
  FxCustomFire = 84,
  FxCustomMutateHalo = 85,
  FxCustomSolidFadeIn = 86,
  Mind = 87,
  MindCameraman = 88,
  MindCinema = 89,
  MindHuman = 90,
  MindPlayer = 91,
  MiscAnimDelete = 92,
  MiscAnimatedLight = 93,
  MiscButtonBat = 94,
  MiscChickenEgg = 95,
  MiscFurnace = 96,
  MiscGhoulyKey = 97,
  MiscKnockDownSphere = 98,
  MiscMummyCursedSlabTop = 99,
  MiscProp = 100,
  MiscSSSDoor = 101,
  MiscSSSDropper = 102,
  MiscScare = 103,
  MiscScareFigure = 104,
  MiscSpiderWeb = 105,
  MiscSuperScaryShock = 106,
  Move = 107,
  Powerup = 108,
  SceneControl = 109,
  Spawn = 110,
  State = 111,
  Strategy = 112,
  StrategyDirector = 113,
  StrategyHauntedCoat = 114,
  StrategyHauntedDoor = 115,
  StrategyHuman = 116,
  StrategyPlayer = 117,
  Weapon = 118,
  WeaponAnchor = 119,
  WeaponAnkh = 120,
  WeaponAnvil = 121,
  WeaponBandage = 122,
  WeaponBaronCane = 123,
  WeaponBarrel = 124,
  WeaponBathtub = 125,
  WeaponBellows = 126,
  WeaponBlunderbuss = 127,
  WeaponBook = 128,
  WeaponBottle = 129,
  WeaponBottleContainer = 130,
  WeaponBroom = 131,
  WeaponBurger = 132,
  WeaponBurgerContainer = 133,
  WeaponCake = 134,
  WeaponCandle = 135,
  WeaponCandlestick = 136,
  WeaponChair = 137,
  WeaponChessBoard = 138,
  WeaponChestOfDrawers = 139,
  WeaponChristmasPudding = 140,
  WeaponCoalScuttle = 141,
  WeaponCookingPot = 142,
  WeaponCrate = 143,
  WeaponCrate2 = 144,
  WeaponCrutches = 145,
  WeaponCue = 146,
  WeaponCymbal = 147,
  WeaponDrum = 148,
  WeaponDustbin = 149,
  WeaponDustpan = 150,
  WeaponEgg = 151,
  WeaponEggContainer = 152,
  WeaponFeatherDuster = 153,
  WeaponFeedingTrough = 154,
  WeaponFigurine = 155,
  WeaponFilmReel = 156,
  WeaponFireBall = 157,
  WeaponFireExtinguisher = 158,
  WeaponFishingRod = 159,
  WeaponFlourBag = 160,
  WeaponFrenchStick = 161,
  WeaponFruitBowl = 162,
  WeaponFryingPan = 163,
  WeaponGarlic = 164,
  WeaponGiantScissors = 165,
  WeaponGlassPane = 166,
  WeaponGnome = 167,
  WeaponGramophone = 168,
  WeaponGuitar = 169,
  WeaponHandSaw = 170,
  WeaponHatStand = 171,
  WeaponIroningBoard = 172,
  WeaponJointOfMeat = 173,
  WeaponLaboratoryBed = 174,
  WeaponLadder = 175,
  WeaponLargePlate = 176,
  WeaponLaundryBasket = 177,
  WeaponMailbox = 178,
  WeaponMirror = 179,
  WeaponMummyCurse = 180,
  WeaponOar = 181,
  WeaponOilDrum = 182,
  WeaponPaintBall = 183,
  WeaponPaintCan = 184,
  WeaponPaintCanContainer = 185,
  WeaponPainting = 186,
  WeaponPicnicTable = 187,
  WeaponPirateChest = 188,
  WeaponPirateRum = 189,
  WeaponPirateSword = 190,
  WeaponPitchfork = 191,
  WeaponPlank = 192,
  WeaponPlantPot = 193,
  WeaponPopCan = 194,
  WeaponPopCanGun = 195,
  WeaponPot = 196,
  WeaponPotContainer = 197,
  WeaponPumpkin = 198,
  WeaponRake = 199,
  WeaponRollingPin = 200,
  WeaponSilverServiceTray = 201,
  WeaponSkip = 202,
  WeaponSmallTree = 203,
  WeaponSnookerTable = 204,
  WeaponSofa = 205,
  WeaponSofaButler = 206,
  WeaponSpade = 207,
  WeaponSpeaker = 208,
  WeaponSpecialPot = 209,
  WeaponSpiderSpitBall = 210,
  WeaponStandardLamp = 211,
  WeaponStool = 212,
  WeaponSwordFish = 213,
  WeaponSyringe = 214,
  WeaponSyringeContainer = 215,
  WeaponTable = 216,
  WeaponTableLamp = 217,
  WeaponTelevision = 218,
  WeaponToiletBrush = 219,
  WeaponToiletRoll = 220,
  WeaponToiletRollContainer = 221,
  WeaponToyBox = 222,
  WeaponTreeStump = 223,
  WeaponTrophy = 224,
  WeaponTrunk = 225,
  WeaponUmbrella = 226,
  WeaponVase = 227,
  WeaponWarlockBolt = 228,
  WeaponWashingPowder = 229,
  WeaponWaterPistol = 230,
  WeaponWelly = 231,
  WeaponWheelbarrow = 232,
  WeaponZombieArm = 233
};

class Object
{
public:
  struct ObjectParams;
  virtual ~Object();

  struct ObjectParams
  {
    uint16_t params_size;
    uint16_t obj_init_value;
    uint32_t type_index;
  };

protected:
  explicit Object(const ObjectParams& /*params*/) {};

private:
  uint8_t unknown_1_ {};
  uint8_t unknown_2_ {};
  ObjectType object_type_ {None};
};

}  // namespace ghoulies::objects
