#pragma once

#include <cstdlib>

/// Retrieves a new random number from 0F to 2F. Uses rand under the hood to
/// match the random numbers generated by the original game.
/// WARN: Fix thread safety if the app is made multithreaded.
inline float GetRandomValue()
{
  return static_cast<float>(rand());
}
